#!/bin/bash
# Non-destructive checks for SharedServerTools mail templates and (if installed) Exim.
set -euo pipefail

ROOT=$(dirname "$(dirname "$(realpath "$0")")")
fail=0

echo "== bash syntax =="
for f in "$ROOT"/initial-setup.sh "$ROOT"/setup-mail.sh "$ROOT"/add-email-domain.sh \
	"$ROOT"/add-website.sh "$ROOT"/remove-website.sh "$ROOT"/tools/*.sh; do
	if ! bash -n "$f"; then
		echo "FAIL: bash -n $f"
		fail=1
	else
		echo "OK   $f"
	fi
done

echo
echo "== templates: no leftover 2.3 Dovecot names in 2.4 drop-in =="
dovecot_dropin="$ROOT/config-templates/99-sharedservertools-dovecot.conf"
for bad in mail_location ssl_cert ssl_key ssl_dh; do
	if grep -E "^[[:space:]]*${bad}[[:space:]]*=" "$dovecot_dropin"; then
		echo "FAIL: Dovecot 2.3 setting '$bad' in $dovecot_dropin"
		fail=1
	fi
done
for need in ssl_server_cert_file ssl_server_key_file mail_driver mail_path; do
	if ! grep -q "$need" "$dovecot_dropin"; then
		echo "FAIL: missing $need in Dovecot drop-in"
		fail=1
	fi
done
echo "OK   Dovecot 2.4 drop-in setting names"

echo
echo "== templates: Exim dsearch lookups =="
if grep -E 'virtual/\$domain[^-_]' "$ROOT"/config-templates/350_exim4-config_vdom_aliases \
	|| grep -E 'virtual/\$domain"' "$ROOT"/config-templates/350_exim4-config_vdom_aliases; then
	echo "FAIL: router still uses \$domain in a path"
	fail=1
fi
if ! grep -q 'dsearch' "$ROOT"/config-templates/350_exim4-config_vdom_aliases; then
	echo "FAIL: virtual router missing dsearch"
	fail=1
fi
if ! grep -q 'dsearch' "$ROOT"/config-templates/00_local_macros; then
	echo "FAIL: DKIM macros missing dsearch"
	fail=1
fi
if grep -q 'tls_on_connect_ports = 465 : 587' "$ROOT"/config-templates/00_local_macros; then
	echo "FAIL: port 587 must not be TLS-on-connect"
	fail=1
fi
echo "OK   Exim templates use dsearch / \$domain_data"

echo
echo "== templates: Maildir modes =="
if ! grep -q 'MAILDIR_HOME_DIRECTORY_MODE = 0700' "$ROOT"/config-templates/00_local_macros; then
	echo "FAIL: Maildir directory mode should be 0700"
	fail=1
else
	echo "OK   MAILDIR_HOME_DIRECTORY_MODE = 0700"
fi

echo
echo "== placeholders =="
if grep -R '__[A-Z0-9_]*__' "$ROOT"/config-templates/00_local_macros \
	"$ROOT"/config-templates/99-sharedservertools-dovecot.conf \
	"$ROOT"/config-templates/default | grep -v '__HOSTNAME_\|__PHP_\|__PRIMARY_'; then
	echo "(info) leftover placeholders shown above if any unexpected"
fi

if command -v exim4 >/dev/null 2>&1; then
	echo
	echo "== installed Exim =="
	exim4 -bV | head -n 8
	if [[ -f /var/lib/exim4/config.autogenerated ]]; then
		if grep -n 'Tainted' /var/log/exim4/mainlog 2>/dev/null | tail -n 5; then
			true
		fi
		echo "OK   exim4 binary present"
	fi
else
	echo
	echo "(exim4 not installed here; skipped live binary checks)"
fi

if [[ "$fail" -ne 0 ]]; then
	echo
	echo "Some checks failed."
	exit 1
fi
echo
echo "All checks passed."
